---
version: 1.1.0
slug: cups
name: CUPS Print Server
description: CUPS print server for network printing
url: https://github.com/arest/cups-addon
codenotary: andrea_restello@yahoo.it
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
build_from:
  armhf: ghcr.io/home-assistant/armhf-base:latest
  armv7: ghcr.io/home-assistant/armv7-base:latest
  aarch64: ghcr.io/home-assistant/aarch64-base:latest
  amd64: ghcr.io/home-assistant/amd64-base:latest
  i386: ghcr.io/home-assistant/i386-base:latest
hassio_api: true
host_network: true
map:
  - data:rw
  - share:rw
init: false
ports:
  631/tcp: 631
ports_description:
  631/tcp: CUPS web interface and printing port
options:
  admin_username: "admin"
  admin_password: "admin"
  printer_driver_deb: ""
schema:
  admin_username: str
  admin_password: password
  printer_driver_deb: str
startup: services
